import { Container } from 'inversify';
import { Component } from './container.types.js';
import { Application } from '../../application/application.js';
import { Logger } from '../libs/logger/logger.interface.js';
import { PinoLogger } from '../libs/logger/pino.logger.js';
import { AppConfig, appConfig } from '../config/config.js';
import { DatabaseClient } from '../libs/database/database.interface.js';
import { MongoDatabaseClient } from '../libs/database/mongo.database-client.js';
import { UserService } from '../modules/user/user-service.interface.js';
import { DefaultUserService } from '../modules/user/user.service.js';
import { CityService } from '../modules/city/city-service.interface.js';
import { DefaultCityService } from '../modules/city/city.service.js';
import { OfferService } from '../modules/offer/offer-service.interface.js';
import { DefaultOfferService } from '../modules/offer/offer.service.js';
import { CommentService } from '../modules/comment/comment-service.interface.js';
import { DefaultCommentService } from '../modules/comment/comment.service.js';
import { TokenService } from '../libs/token/token-service.interface.js';
import { InMemoryTokenService } from '../libs/token/in-memory-token.service.js';
import { PrivateRouteMiddleware } from '../http/middleware/private-route.middleware.js';
import { ValidateObjectIdMiddleware } from '../http/middleware/validate-objectid.middleware.js';
import { ValidateDtoMiddleware } from '../http/middleware/validate-dto.middleware.js';
import { UserController } from '../modules/user/controller/user.controller.js';
import { OfferController } from '../modules/offer/controller/offer.controller.js';
import { CommentController } from '../modules/comment/controller/comment.controller.js';
import { Controller } from '../http/types/controller.interface.js';
import { HttpExceptionFilter } from '../http/exception-filter/http-exception.filter.js';
import { UnknownExceptionFilter } from '../http/exception-filter/unknown-exception.filter.js';
import { ExceptionFilter } from '../http/exception-filter/exception-filter.interface.js';

const container = new Container();

container.bind<Application>(Component.Application).to(Application).inSingletonScope();
container.bind<Logger>(Component.Logger).to(PinoLogger).inSingletonScope();
container.bind<AppConfig>(Component.Config).toConstantValue(appConfig);
container.bind<DatabaseClient>(Component.DatabaseClient).to(MongoDatabaseClient).inSingletonScope();
container.bind<TokenService>(Component.TokenService).to(InMemoryTokenService).inSingletonScope();
container.bind<UserService>(Component.UserService).to(DefaultUserService).inSingletonScope();
container.bind<CityService>(Component.CityService).to(DefaultCityService).inSingletonScope();
container.bind<OfferService>(Component.OfferService).to(DefaultOfferService).inSingletonScope();
container.bind<CommentService>(Component.CommentService).to(DefaultCommentService).inSingletonScope();
container.bind<PrivateRouteMiddleware>(Component.PrivateRouteMiddleware).to(PrivateRouteMiddleware).inSingletonScope();
container.bind<ValidateObjectIdMiddleware>(Component.ValidateObjectIdMiddleware).to(ValidateObjectIdMiddleware).inSingletonScope();
container.bind<ValidateDtoMiddleware>(Component.ValidateDtoMiddleware).to(ValidateDtoMiddleware).inSingletonScope();
container.bind<Controller>(Component.UserController).to(UserController).inSingletonScope();
container.bind<Controller>(Component.OfferController).to(OfferController).inSingletonScope();
container.bind<Controller>(Component.CommentController).to(CommentController).inSingletonScope();
container.bind<ExceptionFilter>(Component.HttpExceptionFilter).to(HttpExceptionFilter).inSingletonScope();
container.bind<ExceptionFilter>(Component.UnknownExceptionFilter).to(UnknownExceptionFilter).inSingletonScope();

export { container };
