export const Component = {
  Application: Symbol.for('Application'),
  HttpExceptionFilter: Symbol.for('HttpExceptionFilter'),
  UnknownExceptionFilter: Symbol.for('UnknownExceptionFilter'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  TokenService: Symbol.for('TokenService'),
  PrivateRouteMiddleware: Symbol.for('PrivateRouteMiddleware'),
  ValidateObjectIdMiddleware: Symbol.for('ValidateObjectIdMiddleware'),
  ValidateDtoMiddleware: Symbol.for('ValidateDtoMiddleware'),
  DocumentExistsMiddleware: Symbol.for('DocumentExistsMiddleware'),
  UploadFileMiddleware: Symbol.for('UploadFileMiddleware'),
  UserController: Symbol.for('UserController'),
  OfferController: Symbol.for('OfferController'),
  CommentController: Symbol.for('CommentController'),
  UserService: Symbol.for('UserService'),
  CityService: Symbol.for('CityService'),
  OfferService: Symbol.for('OfferService'),
  CommentService: Symbol.for('CommentService'),
} as const;
